# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='img',
            field=models.CharField(default='darksoulsimg/main_show.jpg', max_length=255),
        ),
    ]
